In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
sns.set_style("darkgrid")

In [2]:
data = pd.read_csv('/Users/Mariwa/.bitnami/stackman/machines/xampp/volumes/root/htdocs/HomeExchange/tier match/tier_dataset.csv')
X = data.iloc[:,:-1].values
Y = data.iloc[:, 15].values
data.head(2000)

Swimming Pool  Home Type  Residence Type  WiFi  TV  AC  Private Gym  \
0               1          1               1     1   1   1            1   
1               1          1               1     1   1   1            1   
2               1          1               1     1   1   1            1   
3               1          1               0     1   1   1            1   
4               1          1               0     1   1   1            1   
..            ...        ...             ...   ...  ..  ..          ...   
60              0          0               0     0   0   0            0   
61              0          0               1     1   0   1            0   
62              0          0               0     1   1   0            0   
63              0          0               0     0   0   1            0   
64              0          0               0     0   1   0            0   

    Parking  Wheelchair Accessibility  Pets Allowed  Kids Friendly  \
0         1                         1             1              1   
1         1                         1             1              1   
2         0                         1             1              1   
3         1                         0             0              1   
4         0                         0             1              1   
..      ...                       ...           ...            ...   
60        0                         0             0              0   
61        0                         1             0              0   
62        0                         0             0              0   
63        0                         0             0              0   
64        0                         0             0              1   

    Home Workers  Security Guard  Private Garden  Smokers Allowed  Tier  
0              1               1               1                1     1  
1              1               1               1                0     1  
2              1               1               1                0     1  
3              1               1               1                1     1  
4              1               1               1                1     1  
..           ...             ...             ...              ...   ...  
60             0               0               0                1     5  
61             0               0               0                0     5  
62             0               0               0                0     5  
63             0               1               0                1     5  
64             0               0               0                0     5  

[65 rows x 16 columns]

In [3]:
data.describe()

Swimming Pool  Home Type  Residence Type       WiFi         TV  \
count      65.000000   65.00000       65.000000  65.000000  65.000000   
mean        0.276923    0.40000        0.338462   0.861538   0.707692   
std         0.450961    0.49371        0.476869   0.348072   0.458362   
min         0.000000    0.00000        0.000000   0.000000   0.000000   
25%         0.000000    0.00000        0.000000   1.000000   0.000000   
50%         0.000000    0.00000        0.000000   1.000000   1.000000   
75%         1.000000    1.00000        1.000000   1.000000   1.000000   
max         1.000000    1.00000        1.000000   1.000000   1.000000   

              AC  Private Gym    Parking  Wheelchair Accessibility  \
count  65.000000    65.000000  65.000000                 65.000000   
mean    0.507692     0.446154   0.446154                  0.446154   
std     0.503831     0.500961   0.500961                  0.500961   
min     0.000000     0.000000   0.000000                  0.000000   
25%     0.000000     0.000000   0.000000                  0.000000   
50%     1.000000     0.000000   0.000000                  0.000000   
75%     1.000000     1.000000   1.000000                  1.000000   
max     1.000000     1.000000   1.000000                  1.000000   

       Pets Allowed  Kids Friendly  Home Workers  Security Guard  \
count     65.000000      65.000000     65.000000       65.000000   
mean       0.338462       0.707692      0.630769        0.661538   
std        0.476869       0.458362      0.486352        0.476869   
min        0.000000       0.000000      0.000000        0.000000   
25%        0.000000       0.000000      0.000000        0.000000   
50%        0.000000       1.000000      1.000000        1.000000   
75%        1.000000       1.000000      1.000000        1.000000   
max        1.000000       1.000000      1.000000        1.000000   

       Private Garden  Smokers Allowed       Tier  
count       65.000000        65.000000  65.000000  
mean         0.646154         0.384615   3.015385  
std          0.481883         0.490290   1.408593  
min          0.000000         0.000000   1.000000  
25%          0.000000         0.000000   2.000000  
50%          1.000000         0.000000   3.000000  
75%          1.000000         1.000000   4.000000  
max          1.000000         1.000000   5.000000

In [4]:
X

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1],
       [1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0],
       [1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0],
       [0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0],
       [0, 0, 0, 1, 1, 1, 1,

In [188]:
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.1)

In [6]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train,Y_train)

KNeighborsClassifier()

In [8]:
y_pred = classifier.predict(X_test)

In [9]:
print(classification_report(Y_test,y_pred))
print(confusion_matrix(Y_test, y_pred))

              precision    recall  f1-score   support

           3       1.00      1.00      1.00         3
           4       0.50      1.00      0.67         1
           5       1.00      0.67      0.80         3

    accuracy                           0.86         7
   macro avg       0.83      0.89      0.82         7
weighted avg       0.93      0.86      0.87         7

[[3 0 0]
 [0 1 0]
 [0 1 2]]


In [10]:
check_value = np.array([0,0,1,1,1,0,1,0,0,1,1,1,1,0,0])

In [11]:
tier_prediction = classifier.predict([check_value])

In [12]:
tier_prediction

array([1])