In [638]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import neighbors
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from matplotlib.colors import ListedColormap
from sklearn.metrics import classification_report, confusion_matrix
import pickle
sns.set_style("darkgrid")

In [639]:
data = pd.read_csv('/Applications/XAMPP/xamppfiles/htdocs/HomeExchange/tiermatch/home_tier_dataset2.csv')
X = data.iloc[:,:-1].values
Y = data.iloc[:, 18].values
data.head(176)

Swimming Pool  Home Type  Residence Type  WiFi  TV  AC  Bedrooms  \
0                0          1               1     1   0   0         3   
1                1          0               1     1   1   1         7   
2                0          0               1     1   1   1         3   
3                1          1               1     1   1   1         4   
4                1          1               1     1   1   1         3   
..             ...        ...             ...   ...  ..  ..       ...   
170              1          0               1     1   1   1         7   
171              0          0               1     1   0   1         2   
172              0          1               1     1   1   1         4   
173              0          0               0     1   0   0         3   
174              1          1               1     1   1   1         4   

     Bathrooms  Capacity  Private Gym  Parking  Wheelchair Accessibility  \
0            1         5            0        0                         0   
1            4        13            1        1                         1   
2            1         6            1        1                         1   
3            4         5            1        1                         0   
4            2         5            1        1                         1   
..         ...       ...          ...      ...                       ...   
170          4         9            1        1                         1   
171          2         2            0        0                         1   
172          2         8            1        1                         0   
173          1         5            1        0                         1   
174          2         4            1        0                         1   

     Pets Allowed  Kids Friendly  Home Workers  Security Guard  \
0               0              0             0               0   
1               1              1             1               1   
2               1              1             1               1   
3               1              1             1               1   
4               1              1             1               1   
..            ...            ...           ...             ...   
170             0              1             1               1   
171             0              0             0               0   
172             0              1             1               1   
173             0              0             0               0   
174             1              1             1               1   

     Private Garden  Smokers Allowed  Tier  
0                 0                0     5  
1                 1                0     1  
2                 1                0     2  
3                 1                0     1  
4                 1                0     1  
..              ...              ...   ...  
170               1                1     1  
171               0                0     5  
172               1                1     2  
173               0                1     4  
174               1                0     1  

[175 rows x 19 columns]

In [640]:
data.describe()

Swimming Pool   Home Type  Residence Type        WiFi          TV  \
count     175.000000  175.000000      175.000000  175.000000  175.000000   
mean        0.262857    0.405714        0.331429    0.845714    0.720000   
std         0.441449    0.492439        0.472077    0.362259    0.450287   
min         0.000000    0.000000        0.000000    0.000000    0.000000   
25%         0.000000    0.000000        0.000000    1.000000    0.000000   
50%         0.000000    0.000000        0.000000    1.000000    1.000000   
75%         1.000000    1.000000        1.000000    1.000000    1.000000   
max         1.000000    1.000000        1.000000    1.000000    1.000000   

               AC    Bedrooms   Bathrooms    Capacity  Private Gym  \
count  175.000000  175.000000  175.000000  175.000000   175.000000   
mean     0.554286    3.514286    2.228571    5.645714     0.440000   
std      0.498471    1.508052    1.041819    2.339116     0.497811   
min      0.000000    1.000000    1.000000    1.000000     0.000000   
25%      0.000000    2.500000    1.000000    4.000000     0.000000   
50%      1.000000    3.000000    2.000000    5.000000     0.000000   
75%      1.000000    4.000000    3.000000    7.000000     1.000000   
max      1.000000    8.000000    5.000000   13.000000     1.000000   

          Parking  Wheelchair Accessibility  Pets Allowed  Kids Friendly  \
count  175.000000                175.000000    175.000000     175.000000   
mean     0.525714                  0.451429      0.400000       0.691429   
std      0.500771                  0.499063      0.491304       0.463229   
min      0.000000                  0.000000      0.000000       0.000000   
25%      0.000000                  0.000000      0.000000       0.000000   
50%      1.000000                  0.000000      0.000000       1.000000   
75%      1.000000                  1.000000      1.000000       1.000000   
max      1.000000                  1.000000      1.000000       1.000000   

       Home Workers  Security Guard  Private Garden  Smokers Allowed  \
count    175.000000      175.000000      175.000000       175.000000   
mean       0.640000        0.674286        0.657143         0.417143   
std        0.481377        0.469986        0.476026         0.494502   
min        0.000000        0.000000        0.000000         0.000000   
25%        0.000000        0.000000        0.000000         0.000000   
50%        1.000000        1.000000        1.000000         0.000000   
75%        1.000000        1.000000        1.000000         1.000000   
max        1.000000        1.000000        1.000000         1.000000   

             Tier  
count  175.000000  
mean     3.005714  
std      1.428355  
min      1.000000  
25%      2.000000  
50%      3.000000  
75%      4.000000  
max      5.000000

In [641]:
X

array([[0, 1, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 1, 1, 0],
       [0, 0, 1, ..., 1, 1, 0],
       ...,
       [0, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [1, 1, 1, ..., 1, 1, 0]])

In [642]:
Y

array([5, 1, 2, 1, 1, 2, 2, 1, 3, 3, 2, 4, 4, 1, 4, 4, 4, 5, 5, 3, 5, 5,
       4, 1, 4, 5, 5, 4, 2, 3, 1, 5, 1, 5, 1, 1, 3, 1, 5, 3, 4, 3, 5, 2,
       4, 3, 2, 1, 1, 4, 4, 1, 3, 3, 3, 3, 2, 3, 2, 1, 2, 3, 5, 4, 3, 4,
       2, 3, 1, 1, 3, 4, 2, 3, 4, 3, 3, 4, 5, 1, 2, 5, 4, 5, 3, 2, 4, 5,
       4, 5, 2, 5, 3, 3, 5, 5, 2, 1, 4, 3, 5, 5, 2, 2, 1, 2, 2, 4, 4, 4,
       3, 5, 2, 4, 4, 2, 2, 1, 1, 5, 1, 1, 5, 3, 1, 1, 3, 2, 3, 2, 3, 2,
       3, 5, 2, 5, 2, 4, 1, 5, 5, 4, 1, 4, 2, 3, 2, 2, 4, 1, 5, 5, 3, 5,
       2, 1, 3, 1, 5, 2, 5, 1, 4, 5, 5, 2, 3, 3, 1, 3, 1, 5, 2, 4, 1])

In [644]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.5,random_state=42)

In [594]:
#scaler = StandardScaler()
#scaler.fit(X_train)
#X_train = scaler.transform(X_train)
#X_test = scaler.transform(X_test)

In [645]:
classifier = KNeighborsClassifier(n_neighbors=5)
classfifier = RandomForestClassifier()
classifier.fit(X_train,Y_train)

KNeighborsClassifier()

In [646]:
y_pred = classifier.predict(X_test)

In [663]:
print(classification_report(Y_test,y_pred))
print(confusion_matrix(Y_test, y_pred))

              precision    recall  f1-score   support

           1       0.88      0.79      0.83        19
           2       0.53      0.67      0.59        15
           3       0.71      0.75      0.73        20
           4       0.88      0.39      0.54        18
           5       0.70      1.00      0.82        16

    accuracy                           0.72        88
   macro avg       0.74      0.72      0.70        88
weighted avg       0.75      0.72      0.71        88

[[15  4  0  0  0]
 [ 2 10  3  0  0]
 [ 0  4 15  1  0]
 [ 0  1  3  7  7]
 [ 0  0  0  0 16]]


In [660]:
check_value = np.array([1,0,0,1,1,1,3,2,7,1,0,0,1,1,0,1,1,1])
check_value = check_value.reshape(1,-1)

In [661]:
tier_prediction = classifier.predict(check_value)

In [662]:
tier_prediction[0]

4

In [585]:
with open('tier_model_pickle', 'wb') as f:
    pickle.dump(classifier,f)

In [586]:
with open('tier_model_pickle','rb') as f:
    classifier = pickle.load(f)

In [587]:
y_pred = classifier.predict(X_test)

In [588]:
print(classification_report(Y_test,y_pred))
print(confusion_matrix(Y_test, y_pred))

              precision    recall  f1-score   support

           1       0.82      0.52      0.64        27
           2       0.41      0.76      0.53        21
           3       0.73      0.62      0.67        26
           4       0.67      0.08      0.14        25
           5       0.57      1.00      0.73        24

    accuracy                           0.59       123
   macro avg       0.64      0.60      0.54       123
weighted avg       0.65      0.59      0.54       123

[[14 13  0  0  0]
 [ 3 16  2  0  0]
 [ 0  9 16  1  0]
 [ 0  1  4  2 18]
 [ 0  0  0  0 24]]
