In [27]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import neighbors
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from matplotlib.colors import ListedColormap
from sklearn.metrics import classification_report, confusion_matrix
import pickle
sns.set_style("darkgrid")

In [28]:
data = pd.read_csv('/Users/Mariwa/.bitnami/stackman/machines/xampp/volumes/root/htdocs/HomeExchange/tier match/home_tier_dataset.csv')
X = data.iloc[:,:-1].values
Y = data.iloc[:, 18].values
data.head(2000)

Swimming Pool  Home Type  Residence Type  WiFi  TV  AC  Bedrooms  \
0                1          1               1     1   1   1         5   
1                1          1               1     1   1   1         3   
2                1          1               1     1   1   1         4   
3                1          1               0     1   1   1         8   
4                1          1               0     1   1   1         3   
..             ...        ...             ...   ...  ..  ..       ...   
115              0          0               1     0   0   0         3   
116              0          0               1     0   0   1         3   
117              0          1               1     0   0   0         3   
118              0          0               1     0   0   0         3   
119              0          0               0     0   1   1         3   

     Bathrooms  Capacity  Private Gym  Parking  Wheelchair Accessibility  \
0            3         8            1        1                         1   
1            2         5            1        1                         1   
2            2         4            1        0                         1   
3            4        12            1        1                         0   
4            1         4            1        0                         0   
..         ...       ...          ...      ...                       ...   
115          2         3            0        0                         1   
116          3         3            0        1                         0   
117          3         4            0        0                         0   
118          2         4            0        0                         0   
119          2         6            0        0                         0   

     Pets Allowed  Kids Friendly  Home Workers  Security Guard  \
0               1              1             1               1   
1               1              1             1               1   
2               1              1             1               1   
3               0              1             1               1   
4               1              1             1               1   
..            ...            ...           ...             ...   
115             0              0             0               0   
116             0              0             0               0   
117             0              0             0               0   
118             1              1             0               0   
119             0              0             0               1   

     Private Garden  Smokers Allowed  Tier  
0                 1                1     1  
1                 1                0     1  
2                 1                0     1  
3                 1                1     1  
4                 1                1     1  
..              ...              ...   ...  
115               0                1     5  
116               0                0     5  
117               0                1     5  
118               0                0     5  
119               0                0     5  

[120 rows x 19 columns]

In [29]:
data.describe()

Swimming Pool   Home Type  Residence Type        WiFi          TV  \
count     120.000000  120.000000      120.000000  120.000000  120.000000   
mean        0.300000    0.425000        0.341667    0.858333    0.716667   
std         0.460179    0.496416        0.476257    0.350170    0.452506   
min         0.000000    0.000000        0.000000    0.000000    0.000000   
25%         0.000000    0.000000        0.000000    1.000000    0.000000   
50%         0.000000    0.000000        0.000000    1.000000    1.000000   
75%         1.000000    1.000000        1.000000    1.000000    1.000000   
max         1.000000    1.000000        1.000000    1.000000    1.000000   

              AC    Bedrooms   Bathrooms    Capacity  Private Gym     Parking  \
count  120.00000  120.000000  120.000000  120.000000   120.000000  120.000000   
mean     0.55000    3.450000    2.108333    5.558333     0.458333    0.500000   
std      0.49958    1.494247    0.985575    2.465888     0.500350    0.502096   
min      0.00000    1.000000    1.000000    1.000000     0.000000    0.000000   
25%      0.00000    2.000000    1.000000    4.000000     0.000000    0.000000   
50%      1.00000    3.000000    2.000000    5.000000     0.000000    0.500000   
75%      1.00000    4.000000    3.000000    7.000000     1.000000    1.000000   
max      1.00000    8.000000    5.000000   13.000000     1.000000    1.000000   

       Wheelchair Accessibility  Pets Allowed  Kids Friendly  Home Workers  \
count                 120.00000    120.000000     120.000000    120.000000   
mean                    0.45000      0.358333       0.708333      0.658333   
std                     0.49958      0.481521       0.456435      0.476257   
min                     0.00000      0.000000       0.000000      0.000000   
25%                     0.00000      0.000000       0.000000      0.000000   
50%                     0.00000      0.000000       1.000000      1.000000   
75%                     1.00000      1.000000       1.000000      1.000000   
max                     1.00000      1.000000       1.000000      1.000000   

       Security Guard  Private Garden  Smokers Allowed        Tier  
count      120.000000      120.000000       120.000000  120.000000  
mean         0.683333        0.666667         0.433333    2.925000  
std          0.467127        0.473381         0.497613    1.444564  
min          0.000000        0.000000         0.000000    1.000000  
25%          0.000000        0.000000         0.000000    2.000000  
50%          1.000000        1.000000         0.000000    3.000000  
75%          1.000000        1.000000         1.000000    4.000000  
max          1.000000        1.000000         1.000000    5.000000

In [30]:
X

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 1, 1, 0],
       ...,
       [0, 1, 1, ..., 0, 0, 1],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]])

In [31]:
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [32]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.7)

In [33]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [34]:
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train,Y_train)

KNeighborsClassifier()

In [35]:
y_pred = classifier.predict(X_test)

In [10]:
print(classification_report(Y_test,y_pred))
print(confusion_matrix(Y_test, y_pred))

              precision    recall  f1-score   support

           1       1.00      0.86      0.93        22
           2       0.75      0.92      0.83        13
           3       0.82      1.00      0.90        14
           4       0.92      0.67      0.77        18
           5       0.84      0.94      0.89        17

    accuracy                           0.87        84
   macro avg       0.87      0.88      0.86        84
weighted avg       0.88      0.87      0.87        84

[[19  3  0  0  0]
 [ 0 12  1  0  0]
 [ 0  0 14  0  0]
 [ 0  1  2 12  3]
 [ 0  0  0  1 16]]


In [36]:
check_value = np.array([0,0,1,1,1,0,5,3,7,1,0,0,1,1,1,1,0,0])

In [37]:
tier_prediction = classifier.predict([check_value])

In [38]:
tier_prediction

array([1])

In [39]:
with open('tier_model_pickle', 'wb') as f:
    pickle.dump(classifier,f)

In [24]:
with open('tier_model_pickle','rb') as f:
    classifier = pickle.load(f)

In [25]:
y_pred = classifier.predict(X_test)

In [26]:
print(classification_report(Y_test,y_pred))
print(confusion_matrix(Y_test, y_pred))

              precision    recall  f1-score   support

           1       1.00      0.86      0.93        22
           2       0.75      0.92      0.83        13
           3       0.82      1.00      0.90        14
           4       0.92      0.67      0.77        18
           5       0.84      0.94      0.89        17

    accuracy                           0.87        84
   macro avg       0.87      0.88      0.86        84
weighted avg       0.88      0.87      0.87        84

[[19  3  0  0  0]
 [ 0 12  1  0  0]
 [ 0  0 14  0  0]
 [ 0  1  2 12  3]
 [ 0  0  0  1 16]]
