In [68]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import neighbors
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from matplotlib.colors import ListedColormap
from sklearn.metrics import classification_report, confusion_matrix
import pickle
sns.set_style("darkgrid")

In [69]:
data = pd.read_csv('/Applications/XAMPP/xamppfiles/htdocs/HomeExchange/tiermatch/home_tier_dataset2.csv')
X = data.iloc[:,:-1].values
Y = data.iloc[:, 18].values
data.head(267)

Swimming Pool  Home Type  Residence Type  WiFi  TV  AC  Bedrooms  \
0                1          0               0     1   1   1         8   
1                0          1               1     1   0   0         2   
2                0          0               0     0   0   0         1   
3                0          0               0     1   1   1         2   
4                0          0               1     1   1   1         4   
..             ...        ...             ...   ...  ..  ..       ...   
261              0          0               1     1   0   0         3   
262              0          1               1     1   1   0         4   
263              1          1               0     1   1   1         7   
264              1          0               0     1   1   1         3   
265              0          0               0     1   1   1         5   

     Bathrooms  Capacity  Private Gym  Parking  Wheelchair Accessibility  \
0            6        13            1        1                         1   
1            1         5            1        0                         0   
2            1         1            0        0                         0   
3            2         2            0        0                         1   
4            2         7            1        0                         1   
..         ...       ...          ...      ...                       ...   
261          1         4            0        0                         1   
262          3         7            0        0                         0   
263          5         8            1        1                         0   
264          3         5            1        1                         1   
265          5         9            0        1                         0   

     Pets Allowed  Kids Friendly  Home Workers  Security Guard  \
0               1              1             1               1   
1               0              0             0               1   
2               0              0             0               0   
3               0              1             1               1   
4               0              1             1               1   
..            ...            ...           ...             ...   
261             0              0             0               0   
262             0              1             1               1   
263             1              1             1               1   
264             1              1             1               1   
265             0              1             1               1   

     Private Garden  Smokers Allowed  Tier  
0                 1                1     1  
1                 0                0     4  
2                 0                0     5  
3                 1                0     3  
4                 1                0     2  
..              ...              ...   ...  
261               0                0     5  
262               1                0     3  
263               1                1     1  
264               1                1     1  
265               1                0     3  

[266 rows x 19 columns]

In [70]:
data.describe()

Swimming Pool   Home Type  Residence Type        WiFi          TV  \
count     266.000000  266.000000      266.000000  266.000000  266.000000   
mean        0.259398    0.413534        0.349624    0.864662    0.725564   
std         0.439131    0.493395        0.477750    0.342729    0.447071   
min         0.000000    0.000000        0.000000    0.000000    0.000000   
25%         0.000000    0.000000        0.000000    1.000000    0.000000   
50%         0.000000    0.000000        0.000000    1.000000    1.000000   
75%         1.000000    1.000000        1.000000    1.000000    1.000000   
max         1.000000    1.000000        1.000000    1.000000    1.000000   

               AC    Bedrooms   Bathrooms    Capacity  Private Gym  \
count  266.000000  266.000000  266.000000  266.000000   266.000000   
mean     0.560150    3.684211    2.417293    5.984962     0.451128   
std      0.497304    1.610665    1.318490    2.629255     0.498544   
min      0.000000    1.000000    1.000000    1.000000     0.000000   
25%      0.000000    2.250000    1.000000    4.000000     0.000000   
50%      1.000000    3.000000    2.000000    6.000000     0.000000   
75%      1.000000    5.000000    3.000000    8.000000     1.000000   
max      1.000000    8.000000    8.000000   14.000000     1.000000   

          Parking  Wheelchair Accessibility  Pets Allowed  Kids Friendly  \
count  266.000000                266.000000    266.000000     266.000000   
mean     0.515038                  0.469925      0.424812       0.710526   
std      0.500716                  0.500035      0.495246       0.454373   
min      0.000000                  0.000000      0.000000       0.000000   
25%      0.000000                  0.000000      0.000000       0.000000   
50%      1.000000                  0.000000      0.000000       1.000000   
75%      1.000000                  1.000000      1.000000       1.000000   
max      1.000000                  1.000000      1.000000       1.000000   

       Home Workers  Security Guard  Private Garden  Smokers Allowed  \
count    266.000000      266.000000      266.000000       266.000000   
mean       0.657895        0.680451        0.657895         0.406015   
std        0.475309        0.467181        0.475309         0.492013   
min        0.000000        0.000000        0.000000         0.000000   
25%        0.000000        0.000000        0.000000         0.000000   
50%        1.000000        1.000000        1.000000         0.000000   
75%        1.000000        1.000000        1.000000         1.000000   
max        1.000000        1.000000        1.000000         1.000000   

             Tier  
count  266.000000  
mean     2.977444  
std      1.403318  
min      1.000000  
25%      2.000000  
50%      3.000000  
75%      4.000000  
max      5.000000

In [71]:
X

array([[1, 0, 0, ..., 1, 1, 1],
       [0, 1, 1, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 1, 0, ..., 1, 1, 1],
       [1, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 0]])

In [72]:
Y

array([1, 4, 5, 3, 2, 4, 1, 1, 2, 2, 3, 3, 5, 4, 2, 1, 4, 1, 5, 5, 2, 2,
       4, 3, 2, 1, 5, 3, 1, 5, 1, 3, 3, 4, 4, 2, 3, 1, 5, 4, 1, 2, 3, 2,
       5, 5, 5, 2, 4, 5, 1, 1, 2, 5, 5, 1, 3, 2, 4, 1, 4, 2, 5, 4, 5, 4,
       5, 1, 5, 5, 1, 5, 5, 4, 1, 3, 3, 2, 1, 3, 2, 2, 3, 3, 2, 2, 3, 1,
       5, 1, 2, 5, 5, 5, 1, 5, 4, 2, 5, 1, 3, 1, 1, 5, 3, 4, 5, 5, 1, 4,
       1, 1, 4, 1, 5, 1, 5, 2, 4, 3, 2, 5, 4, 4, 1, 4, 5, 2, 1, 3, 5, 5,
       5, 5, 1, 5, 3, 3, 3, 2, 4, 1, 3, 1, 2, 4, 1, 2, 4, 2, 3, 3, 3, 4,
       4, 1, 3, 4, 4, 1, 1, 3, 4, 2, 4, 2, 4, 4, 5, 3, 2, 2, 2, 1, 5, 1,
       4, 4, 4, 2, 2, 2, 1, 3, 2, 4, 3, 4, 1, 3, 2, 5, 4, 4, 3, 2, 4, 1,
       3, 1, 3, 3, 2, 3, 3, 2, 1, 5, 5, 1, 3, 3, 3, 4, 5, 1, 4, 4, 3, 3,
       3, 2, 3, 4, 3, 5, 3, 3, 2, 1, 4, 5, 3, 5, 5, 2, 3, 2, 1, 4, 2, 3,
       2, 2, 1, 1, 2, 4, 2, 3, 2, 4, 5, 4, 5, 3, 4, 2, 2, 2, 4, 5, 3, 1,
       1, 3])

In [73]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.5,random_state=42)

In [74]:
#scaler = StandardScaler()
#scaler.fit(X_train)
#X_train = scaler.transform(X_train)
#X_test = scaler.transform(X_test)

In [76]:
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train,Y_train)

KNeighborsClassifier()

In [77]:
y_pred = classifier.predict(X_test)

In [78]:
print(classification_report(Y_test,y_pred))
print(confusion_matrix(Y_test, y_pred))

              precision    recall  f1-score   support

           1       0.77      0.69      0.73        29
           2       0.61      0.74      0.67        27
           3       0.79      0.85      0.82        27
           4       1.00      0.39      0.56        28
           5       0.65      1.00      0.79        22

    accuracy                           0.72       133
   macro avg       0.76      0.74      0.71       133
weighted avg       0.77      0.72      0.71       133

[[20  9  0  0  0]
 [ 5 20  2  0  0]
 [ 1  3 23  0  0]
 [ 0  1  4 11 12]
 [ 0  0  0  0 22]]


In [79]:
check_value = np.array([1,0,0,1,1,1,3,2,7,1,0,0,1,1,0,1,1,1])
check_value = check_value.reshape(1,-1)

In [81]:
tier_prediction = classifier.predict(check_value)

In [82]:
tier_prediction[0]

2

In [84]:
with open('tier_model_pickle', 'wb') as f:
    pickle.dump(classifier,f)

In [85]:
with open('tier_model_pickle','rb') as f:
    classifier = pickle.load(f)

In [86]:
y_pred = classifier.predict(X_test)

In [87]:
print(classification_report(Y_test,y_pred))
print(confusion_matrix(Y_test, y_pred))

              precision    recall  f1-score   support

           1       0.77      0.69      0.73        29
           2       0.61      0.74      0.67        27
           3       0.79      0.85      0.82        27
           4       1.00      0.39      0.56        28
           5       0.65      1.00      0.79        22

    accuracy                           0.72       133
   macro avg       0.76      0.74      0.71       133
weighted avg       0.77      0.72      0.71       133

[[20  9  0  0  0]
 [ 5 20  2  0  0]
 [ 1  3 23  0  0]
 [ 0  1  4 11 12]
 [ 0  0  0  0 22]]
